### ISSUE TITLE
request help

### ISSUE THREAD

**Issue by Mankeysocks** [guillerp8/guille_gangsv2#4]
would it be something we could get sum help with KASHacters and using license: / char# ect ive spent last few hr attempting to-do but I'm still missing something 
![bug2](https://user-images.githubusercontent.com/8433086/127099470-cb84f0ae-f70b-4e52-b479-7a63cee03744.png)
![bug1](https://user-images.githubusercontent.com/8433086/127099473-e234e538-9fdb-470e-974c-c529521f792a.png)

love this gang menu Great work

**Comment by Mankeysocks** [comment]
everything works we just cant seem to get it working based on 1 char "all chars get access to gangs due to steam id still been referenced. be dammed if I can work it out little help in right direction would be choice much love mankeysocks

![bug3](https://user-images.githubusercontent.com/8433086/127100035-ea5aeadb-d186-4de3-a353-66fd367ec74d.png)

**Comment by guillerp8** [comment]
Rewritting the resource to work with license
